### ISSUE TITLE
MP-VPN:  Deleted VPNs still exist in the database

### ISSUE THREAD

**Issue by bmah888** [esnet/enos#112]
If we delete VPNs from the vpn service with `vpn kill` or something similar, we should delete the document corresponding to the VPN, as well as update the VPN service object to not include the just-deleted VPN in the `vpns` property.

The user-observable symptom is that after restarting netshell, VPNs that were formerly deleted are still there (or have reappeared).

**Comment by lomaxfrog** [comment]
The documents were not removed when deleting.

**Comment by bmah888** [comment]
This seemed to work correctly when I just tried it.  Closing.
