### ISSUE TITLE
Documentation: Deployment/configuration on testbed hosts.

### ISSUE THREAD

**Issue by jmacauley** [esnet/enos#60]

**Comment by lomaxfrog** [comment]
Not sure what this task is about in the context of the ProxMox deployment (documentation has been written)

**Comment by lomaxfrog** [comment]
There is an existing documentation describing step by step all of the operations. The documentation is internal at the moment (cannot be linked in this bug).

The estimate is raised to 5 to reflect the investigation and experimentation that this documentation required.
