### ISSUE TITLE
the oscars python lib fails when running in standalone

### ISSUE THREAD

**Issue by lomaxfrog** [esnet/enos#77]
The oscars python library fails retrieving the ESnet 5 topology. This causes in turn the testbed topology and other related module to fail in turn.

The problem is that the TopologyFactory uses the local file system to store the bindings between the topology providers and the factory. That facility is not available in standalone mode.

**Comment by bmah888** [comment]
Fixed by esnet/netshell@b7d6ff78fc3a8ebe8cfdfa7a3e51ce35201709fc.  Closing after brief testing.

**Comment by bmah888** [comment]
D'oh.

**Comment by lomaxfrog** [comment]
The python scripts no longer use the TopologyFactory since this relies on the full deployment of netshell (i.e. not unit test nor standalone).
