### ISSUE TITLE
delete resource based on name in Container API

### ISSUE THREAD

**Issue by sowmyab** [esnet/enos#90]
Currently, the deleteResource requires the Resource object to be deleted. It will be useful to have a delete method that deletes based on resource name. (I believe resource names are unique.)

For example, in the IP automation task, I only have the IP address to be deleted and not the IP resource object. So, I need to send an additional query to the database to retrieve the IP resource object and then invoke the delete method. A more efficient way to do this would be to send the IP address to the Container API and ask it to delete the relevant resource.

**Comment by lomaxfrog** [comment]
Yes resource name are unique within a container. I agree this is a desirable feature.

**Comment by lomaxfrog** [comment]
feature implemented in commit 7902fd7..706ceb9  master -> master
