### ISSUE TITLE
Odd behavior by deleteResource in Container API

### ISSUE THREAD

**Issue by sowmyab** [esnet/enos#91]
When I try to delete the IP address after retrieving the IP resource from the database, I noticed an odd behavior. I have to delete the same resource multiple times (the number of times is random) to have it actually purged from the MongoDB database.

**Comment by lomaxfrog** [comment]
Sowmya: can you please provide a python snippet showing how you delete the resource. The following code works deletes the resource from the container, it always works:

from net.es.netshell.api import Container,Resource
import time

r1 = Resource("r1")
c = Container.getContainer("x1")
c.saveResource(r1)

# sleep 30 secs to be sure that the resource cache actually writes it to the db. 
# also gives you the chance to verify with the mongodb shell that the record is there.
time.sleep(30) # <-- to be sure that the resource cache actually writes it to the db. 
                   
r1.delete(c)

**Comment by sowmyab** [comment]
(ipaddress is a string passed from the command line)

ipresource = container.loadResource(ipaddress)
container.deleteResource(ipresource)

**Comment by lomaxfrog** [comment]
Can you try:

ipresource = container.loadResource(ipaddress)
ipresource.delete(container)

**Comment by sowmyab** [comment]
Will that not delete the entire container?

**Comment by lomaxfrog** [comment]
No. 

Eric

**Comment by lomaxfrog** [comment]
The following works for me. That seems similar to your code. I am using mongodb running on the testbed at STAR. Going to try with a local instance.

>>> r1 = Resource("r1")
>>> c = Container.getContainer("x1")
>>> c.saveResource(r1)
>>> c.deleteResource(r1)
>>> c.saveResource(r1)              
>>> c.deleteResource(r1)

**Comment by lomaxfrog** [comment]
Deleting resource works also for me when using a local mongodb instance.

**Comment by sowmyab** [comment]
Can you try loading a resource using its name and then delete it?

**Comment by lomaxfrog** [comment]
Yes I have. With and without restarting netshell between creating the resource and deleting it. Perhaps it would help it you could add a standalone test. Or execute the following and see what happens with your environment:

from net.es.netshell.api import Container,Resource
import time

r1 = Resource("r1")
c = Container.getContainer("x1")
c.saveResource(r1)
r2 = c.loadResource("r1")
c.deleteResource(r2)

**Comment by sowmyab** [comment]
My use case is something like this:
#/usr/bin/python

from net.es.netshell.api import Container,Resource
import time

def delete():
	c = Container.getContainer("x1") 
	r2 = c.loadResource("r1")
	c.deleteResource(r2)

def save():
	r1 = Resource("r1")
	c = Container.getContainer("x1")
	c.saveResource(r1)


if __name__ == '__main__':
    argv = sys.argv

    Container.createContainer("x1")

    if len(argv) == 1:
        print_help()
        sys.exit()
    cmd = argv[1]
    if cmd == "delete":
        delete()
    elif cmd == "save":
    	save()
    else:
    	print "Unknown command"

**Comment by sowmyab** [comment]
`#/usr/bin/python

from net.es.netshell.api import Container,Resource
import time

def delete():
	c = Container.getContainer("x1") 
	r2 = c.loadResource("r1")
	c.deleteResource(r2)

def save():
	r1 = Resource("r1")
	c = Container.getContainer("x1")
	c.saveResource(r1)


if __name__ == '__main__':
    argv = sys.argv

    Container.createContainer("x1")

    if len(argv) == 1:
        print_help()
        sys.exit()
    cmd = argv[1]
    if cmd == "delete":
        delete()
    elif cmd == "save":
    	save()
    else:
    	print "Unknown command"`

**Comment by lomaxfrog** [comment]
Ran the following and it worked. I don't think argument parsing matter.

from net.es.netshell.api import Container,Resource
import time

def delete():
   c = Container.getContainer("x1") 
   r2 = c.loadResource("r1")
   c.deleteResource(r2)

def save():
   r1 = Resource("r1")
   c = Container.getContainer("x1")
   c.saveResource(r1)

save()
delete()

Are you seeing the document r1 in the database  (verify that is indeed the document "r1") ?

**Comment by sowmyab** [comment]
After updating to the latest netshell code, the deleteResource works as expected.

**Comment by lomaxfrog** [comment]
The problem was likely due to a bad installation.
