### ISSUE TITLE
Container API - getContainer 

### ISSUE THREAD

**Issue by sowmyab** [esnet/enos#92]
Currently, getContainer returns null if the container does not exist. It will be useful to have it create the container if it does not exists.

This will make the code using Container APIs more efficient. Otherwise, for every access of the database, the caller has to make an additional query to the database to check if the container exists, if not, create it and then retrieve the container.

**Comment by lomaxfrog** [comment]
I think this is a good idea especially when there high network latency between the client and the server.

**Comment by lomaxfrog** [comment]
Feature implemented in commit 7902fd7
